import { Brain, Sparkles, RefreshCw, Lock } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { aiRepository, extractError } from "@/data/api/ai/aiRepository";

export default function AIInsights({ workouts: _workouts }) {
  const [insight, setInsight] = useState("");
  const [recommendations, setRecommendations] = useState("");
  const [tips, setTips] = useState("");
  
  const [loading, setLoading] = useState(true);
  const [isLocked, setIsLocked] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    fetchInsights();
  }, []);

  const fetchInsights = async () => {
    setLoading(true);
    setIsLocked(false);
    setErrorMessage("");
    try {
      const [insRes, recRes, tipsRes] = await Promise.all([
        aiRepository.getPerformanceInsights(),
        aiRepository.getWorkoutRecommendations(),
        aiRepository.getNutritionTips()
      ]);
      setInsight(insRes?.data?.insight || insRes?.insight || "");
      setRecommendations(recRes?.data?.recommendations || recRes?.recommendations || "");
      setTips(tipsRes?.data?.tips || tipsRes?.tips || "");
    } catch (err) {
      if (err.status === 403) {
        setIsLocked(true);
      } else {
        const parsed = extractError(err);
        setErrorMessage(parsed.message);
      }
    } finally {
      setLoading(false);
    }
  };

  if (isLocked) {
    return (
      <div className="relative p-[1px] bg-gradient-to-br from-orange-500/20 to-transparent rounded-3xl overflow-hidden border border-white/5">
        <div className="bg-black/55 backdrop-blur-2xl p-8 flex flex-col md:flex-row md:items-center justify-between gap-6 relative">
          <div className="space-y-3 max-w-xl">
            <h3 className="text-xl font-bold uppercase tracking-tight text-orange-500 flex items-center gap-2">
              <Lock size={18} /> Premium AI Insights
            </h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              Unlock personalized performance trends, workout suggestions, and dietary tips generated by FitCoach AI using your actual logged fitness history.
            </p>
          </div>
          <Link
            to="/"
            className="py-3 px-6 bg-orange-500 text-black font-black uppercase text-xs rounded-xl hover:bg-orange-400 transition text-center whitespace-nowrap shrink-0"
          >
            Unlock Premium
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-[#111]/40 border border-gray-800 rounded-3xl p-8 relative overflow-hidden space-y-6">
      <div className="absolute top-[-10%] right-[-10%] w-32 h-32 bg-orange-500/5 blur-3xl rounded-full" />
      
      <div className="flex items-center justify-between">
        <h3 className="text-2xl font-black uppercase tracking-tight text-orange-500 flex items-center gap-2">
          <Brain size={22} /> FitCoach AI Analysis
        </h3>
        
        {loading ? (
          <RefreshCw size={16} className="animate-spin text-orange-500" />
        ) : (
          <button
            onClick={fetchInsights}
            className="text-xs uppercase font-bold text-gray-500 hover:text-orange-500 transition"
          >
            Refresh
          </button>
        )}
      </div>

      {loading ? (
        <div className="text-center text-gray-500 text-xs py-8">
          Consulting AI model with your training logs...
        </div>
      ) : errorMessage ? (
        <div className="text-center text-red-400 text-xs py-4 flex flex-col items-center gap-2">
          <span>Failed to retrieve AI insights: {errorMessage}</span>
          <button
            onClick={fetchInsights}
            className="px-4 py-1.5 rounded-lg border border-red-500/20 text-red-400 hover:bg-red-500/10 uppercase tracking-widest text-[10px] font-black"
          >
            Retry
          </button>
        </div>
      ) : (
        <div className="grid md:grid-cols-3 gap-6">
          {/* Performance Summary */}
          <div className="p-5 bg-black/40 rounded-2xl border border-white/5 space-y-2">
            <div className="text-[10px] font-black text-orange-500 uppercase tracking-widest flex items-center gap-1.5">
              <Sparkles size={12} /> Performance Trends
            </div>
            <p className="text-gray-300 text-xs leading-relaxed">
              {insight || "Keep logging workouts to generate consistency insights."}
            </p>
          </div>

          {/* Routine Suggestions */}
          <div className="p-5 bg-black/40 rounded-2xl border border-white/5 space-y-2">
            <div className="text-[10px] font-black text-orange-500 uppercase tracking-widest flex items-center gap-1.5">
              <Sparkles size={12} /> Training Guidance
            </div>
            <p className="text-gray-300 text-xs leading-relaxed">
              {recommendations || "Your recent workout history will formulate new exercise recommendations."}
            </p>
          </div>

          {/* Nutrition Advice */}
          <div className="p-5 bg-black/40 rounded-2xl border border-white/5 space-y-2">
            <div className="text-[10px] font-black text-orange-500 uppercase tracking-widest flex items-center gap-1.5">
              <Sparkles size={12} /> Nutrition Tips
            </div>
            <p className="text-gray-300 text-xs leading-relaxed">
              {tips || "Update your height and weight goals to get custom macronutrient tips."}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}