# Generated by Django 5.2.14 on 2026-05-23 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_subscription',
            field=models.OneToOneField(blank=True, help_text="Optimized link to the user's active subscription tier", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_user', to='subscriptions.subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
    ]
