# Generated by Django 5.2.14 on 2026-05-23 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Body weight in kg', max_digits=5)),
                ('body_fat', models.DecimalField(decimal_places=2, help_text='Body fat percentage %', max_digits=4)),
                ('lean_mass', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated lean muscle mass in kg', max_digits=5)),
                ('fat_mass', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated fat mass in kg', max_digits=5)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Progress Log',
                'verbose_name_plural': 'Progress Logs',
                'db_table': 'progress_progress_log',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
