# Generated by Django 5.2.14 on 2026-05-23 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='progresslog',
            index=models.Index(fields=['user', 'date', 'is_deleted'], name='progress_pr_user_id_f7b16c_idx'),
        ),
    ]
