# Generated by Django 5.2.14 on 2026-05-24 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('calories', models.PositiveIntegerField(help_text='Target calories in kcal')),
                ('protein', models.PositiveIntegerField(help_text='Target protein in grams')),
                ('carbs', models.PositiveIntegerField(help_text='Target carbohydrates in grams')),
                ('fats', models.PositiveIntegerField(help_text='Target fats in grams')),
                ('meals_data', models.JSONField(blank=True, default=dict, help_text='Detailed meal structures')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Nutrition Template',
                'verbose_name_plural': 'Nutrition Templates',
                'db_table': 'core_nutrition_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
