# Generated by Django 5.2.14 on 2026-05-23 22:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'db_table': 'ai_ai_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, default='user', max_length=20)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'db_table': 'ai_ai_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('request_type', models.CharField(choices=[('MACRO_CALCULATION', 'Macro Calculation'), ('CHAT', 'Chat'), ('INSIGHTS', 'Insights')], db_index=True, default='CHAT', max_length=50)),
                ('model_name', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('other', 'Other')], db_index=True, default='gpt-4o', max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated token usage cost in USD', max_digits=10)),
                ('response_time', models.FloatField(default=0.0, help_text='Response time/latency in seconds')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AI Usage',
                'verbose_name_plural': 'AI Usages',
                'db_table': 'ai_ai_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
