# Generated by Django 5.2.14 on 2026-05-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet'), ('other', 'Other')], db_index=True, default='gpt-4o', max_length=50),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Tokens consumed by this message'),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='provider_name',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('GOOGLE', 'Google'), ('OTHER', 'Other')], db_index=True, default='OPENAI', max_length=50),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_ai_messa_convers_ca4739_idx'),
        ),
    ]
