# Generated by Django 6.0.2 on 2026-05-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_update_ai_model_and_provider_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='model_name',
            field=models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Groq)'), ('gpt-4o', 'GPT-4o'), ('other', 'Other')], db_index=True, default='llama-3.3-70b-versatile', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='model_name',
            field=models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant (Groq)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Groq)'), ('gpt-4o', 'GPT-4o'), ('other', 'Other')], db_index=True, default='llama-3.3-70b-versatile', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='provider_name',
            field=models.CharField(choices=[('GROQ', 'Groq'), ('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic'), ('GOOGLE', 'Google'), ('OTHER', 'Other')], db_index=True, default='GROQ', max_length=50),
        ),
    ]
