# Generated by Django 5.2.14 on 2026-05-23 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, help_text='e.g. Chest, Back, Legs', max_length=100)),
                ('equipment', models.JSONField(blank=True, default=list, help_text='List of required equipment')),
                ('muscles', models.JSONField(blank=True, default=list, help_text='List of primary target muscles')),
                ('muscles_secondary', models.JSONField(blank=True, default=list, help_text='List of secondary target muscles')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'workouts_exercise',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('is_blueprint', models.BooleanField(db_index=True, default=False, help_text='True if this is a pre-built program template')),
                ('level', models.CharField(blank=True, help_text='e.g. Beginner, Intermediate, Advanced', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'db_table': 'workouts_workout',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sets', models.PositiveIntegerField(help_text='Number of sets completed')),
                ('reps', models.CharField(help_text="e.g. '8-10', '12', 'AMRAP'", max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight lifted in kg', max_digits=6)),
                ('date', models.DateField(db_index=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Log',
                'verbose_name_plural': 'Workout Logs',
                'db_table': 'workouts_workout_log',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'is_blueprint', 'is_deleted'], name='workouts_wo_user_id_f9763d_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', 'exercise', 'date'], name='workouts_wo_user_id_dc8258_idx'),
        ),
    ]
