# Generated by Django 5.2.14 on 2026-05-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this log is locked and cannot be modified'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this log was locked', null=True),
        ),
    ]
