# Generated by Django 5.2.14 on 2026-05-23 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], db_index=True, default='STRIPE', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=30)),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='Reference/Transaction ID from the bank transfer or payment gateway', max_length=150, null=True)),
                ('proof_image', models.ImageField(blank=True, help_text='Uploaded image proof of payment for manual bank transfers', null=True, upload_to='payment_proofs/')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Stripe charge or transaction session ID', max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
