# Generated by Django 5.2.14 on 2026-05-23 23:12

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Uploaded image proof of payment for manual bank transfers', null=True, upload_to=common.validators.secure_proof_upload_path, validators=[common.validators.validate_secure_image]),
        ),
    ]
